language: go

os:
  - windows
  - linux
  - osx

go:
  - 1.11
  - 1.12
  - 1.13

env:
  - GO111MODULE="yes"

install:
  - if [ "$TRAVIS_OS_NAME" == "windows" ]; then choco install make; fi
  - make setup

script:
 -  make ci

after_success:
  - bash <(curl -s https://codecov.io/bash)
